# alacritty configuration

[window]
decorations = "none"
opacity = 0.95

[window.padding]
x = 5
y = 5

[font]
size   = 11

[font.normal]
family = "HackNerdFontMono"

[font.bold]
family = "HackNerdFontMono"

[font.italic]
family = "HackNerdFontMono"

[font.bold_italic]
family = "HackNerdFontMono"

[colors]
transparent_background_colors = true

[colors.primary]
background = "#111111"
foreground = "#cccccc"

[colors.cursor]
cursor = "CellForeground"
text   = "CellBackground"

[colors.hints.end]
background = "CellBackground"
foreground = "CellForeground"

[colors.hints.start]
background = "CellBackground"
foreground = "CellForeground"

[colors.search.focused_match]
background = "CellBackground"
foreground = "CellForeground"

[colors.search.matches]
background = "CellBackground"
foreground = "CellForeground"

[colors.selection]
background = "CellForeground"
text       = "CellBackground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text   = "CellBackground"

[colors.normal]
black   = "#333333"
red     = "#cc0000"
green   = "#4e9a06"
yellow  = "#c4a000"
blue    = "#3465a4"
magenta = "#75507b"
cyan    = "#06989a"
white   = "#d3d7cf"

[colors.bright]
black   = "#88807c"
red     = "#f15d22"
green   = "#73c48f"
yellow  = "#ffce51"
blue    = "#48b9c7"
magenta = "#ad7fa8"
cyan    = "#34e2e2"
white   = "#eeeeec"

[mouse]
hide_when_typing = true

[scrolling]
history = 2000
